sudo: false
language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
- CC=gcc-7 CXX=g++-7
python:
- '2.7'
- '3.5'
- '3.6'
install:
- sudo apt-get install -y octave liboctave-dev
- echo "pkg install -forge control;pkg install -forge signal;pkg install -forge specfun;" | octave --no-gui
- pip install -e .
- pip install pycodestyle flake8 codecov matplotlib
script:
- python setup.py test
- pycodestyle pysiib.py MI_kraskov test demo
- flake8 pysiib.py MI_kraskov test demo
- cd demo; python demo.py; cd ..
after_success:
- codecov
