sudo: false
language: python
addons:
  apt:
    packages:
      - cmake
      - python3-dev
      - g++-7
python:
- '2.7'
- '3.5'
- '3.6'
install:
- sudo apt-get install -y octave liboctave-dev
- echo "pkg install -forge control;pkg install -forge signal;" | octave --no-gui
- pip install -e .
- pip install pycodestyle flake8 codecov
script:
- python setup.py test
- pycodestyle pysiib.py MI_kraskov test
- flake8 pysiib.py MI_kraskov test
after_success:
- codecov
