name: CI

on: [push, pull_request]

jobs:
  linter_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install python packages
        run: pip install pycodestyle flake8 codecov matplotlib
      - name: install pysiib
        run: pip install -e .
      - name: install for MacOS
        if: runner.os == 'macOS'
        run: |
           brew install octave
           echo "pkg install -forge control;pkg install -forge signal;pkg install -forge specfun;" | sudo octave --no-gui
      - name: install for Linux
        if: runner.os == 'Linux'
        run: |
           sudo apt-get install -y octave liboctave-dev
           echo "pkg install -forge control;pkg install -forge signal;pkg install -forge specfun;" | sudo octave --no-gui
      - name: pycodestyle
        run: pycodestyle pysiib.py MI_kraskov test demo
      - name: flake8
        run: flake8 pysiib.py MI_kraskov test demo
      - name: test
        if: runner.os != 'Windows'
        run: python setup.py test
      - name: demo
        if: runner.os != 'Windows'
        run: cd demo; python demo.py; cd ..
